# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AddNewWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AddNewWindow(object):
    def setupUi(self, AddNewWindow):
        AddNewWindow.setObjectName("AddNewWindow")
        AddNewWindow.resize(800, 54)
        self.centralwidget = QtWidgets.QWidget(AddNewWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame.setStyleSheet(".QFrame {\n"
"    border-radius: 19;\n"
"    background-color: #3E3E3E;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setContentsMargins(5, 5, 5, 5)
        self.gridLayout.setHorizontalSpacing(5)
        self.gridLayout.setVerticalSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.lNewId = QtWidgets.QLabel(self.frame)
        self.lNewId.setMinimumSize(QtCore.QSize(40, 40))
        self.lNewId.setMaximumSize(QtCore.QSize(40, 40))
        self.lNewId.setStyleSheet(".QLabel {\n"
"    border-top-left-radius: 15;\n"
"    border-top-right-radius: 5;\n"
"    border-bottom-right-radius: 5;\n"
"    border-bottom-left-radius: 15;\n"
"    background-color: #282828;\n"
"    color: #13B7E7;\n"
"}")
        self.lNewId.setAlignment(QtCore.Qt.AlignCenter)
        self.lNewId.setObjectName("lNewId")
        self.gridLayout.addWidget(self.lNewId, 0, 0, 1, 1)
        self.inputWrapper = QtWidgets.QFrame(self.frame)
        self.inputWrapper.setStyleSheet("#inputWrapper {\n"
"    background-color: #282828;\n"
"    border-top-left-radius: 5;\n"
"    border-top-right-radius: 15;\n"
"    border-bottom-right-radius: 15;\n"
"    border-bottom-left-radius: 5;\n"
"}")
        self.inputWrapper.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.inputWrapper.setFrameShadow(QtWidgets.QFrame.Raised)
        self.inputWrapper.setObjectName("inputWrapper")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.inputWrapper)
        self.horizontalLayout.setContentsMargins(5, 0, 0, 0)
        self.horizontalLayout.setSpacing(5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.toDoInput = QtWidgets.QLineEdit(self.inputWrapper)
        self.toDoInput.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.toDoInput.setFont(font)
        self.toDoInput.setStyleSheet(".QLineEdit {\n"
"    color: #13B7E7;\n"
"    line-height: 40;\n"
"    background-color: transparent;\n"
"    border: none;\n"
"}")
        self.toDoInput.setObjectName("toDoInput")
        self.horizontalLayout.addWidget(self.toDoInput)
        self.toDoId = QtWidgets.QLabel(self.inputWrapper)
        self.toDoId.setMinimumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setFamily(".Apple Color Emoji UI")
        self.toDoId.setFont(font)
        self.toDoId.setAlignment(QtCore.Qt.AlignCenter)
        self.toDoId.setObjectName("toDoId")
        self.horizontalLayout.addWidget(self.toDoId)
        self.gridLayout.addWidget(self.inputWrapper, 0, 1, 1, 1)
        self.gridLayout_2.addWidget(self.frame, 0, 0, 1, 1)
        AddNewWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(AddNewWindow)
        QtCore.QMetaObject.connectSlotsByName(AddNewWindow)

    def retranslateUi(self, AddNewWindow):
        _translate = QtCore.QCoreApplication.translate
        AddNewWindow.setWindowTitle(_translate("AddNewWindow", "MainWindow"))
        self.lNewId.setText(_translate("AddNewWindow", "#"))
        self.toDoId.setText(_translate("AddNewWindow", "⮐"))
