# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 50)
        MainWindow.setMinimumSize(QtCore.QSize(0, 50))
        MainWindow.setMaximumSize(QtCore.QSize(800, 410))
        MainWindow.setStyleSheet("QMainWindow {\n"
"    border-radius: 20;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(0, 50))
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.fMain = QtWidgets.QFrame(self.centralwidget)
        self.fMain.setMinimumSize(QtCore.QSize(0, 50))
        self.fMain.setStyleSheet("#fMain {\n"
"    background-color: #3e3e3e;\n"
"    border-radius: 19;\n"
"}")
        self.fMain.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fMain.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fMain.setObjectName("fMain")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.fMain)
        self.verticalLayout.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout.setSpacing(5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout.addWidget(self.fMain, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
